task_type: segmentation
dataset_category: cocoseg21
calibration_dataset:
  num_classes: null
  num_frames: 25
  name: modelmaker_seg
  path: /opt/EdgeAIRoot/18423504/projects/25cd3020/dataset
  split: train
  shuffle: true
  annotation_prefix: instances
  dataset_info: /opt/EdgeAIRoot/18423504/projects/25cd3020/run/20250702-165413/deeplabv3plus_mobilenetv2_tv_edgeailite/compilation/AM69A/work/ss-8710/dataset.yaml
input_dataset:
  num_classes: null
  num_frames: 134
  name: modelmaker_seg
  path: /opt/EdgeAIRoot/18423504/projects/25cd3020/dataset
  split: val
  shuffle: false
  annotation_prefix: instances
  dataset_info: /opt/EdgeAIRoot/18423504/projects/25cd3020/run/20250702-165413/deeplabv3plus_mobilenetv2_tv_edgeailite/compilation/AM69A/work/ss-8710/dataset.yaml
preprocess:
  resize:
  - 512
  - 512
  crop:
  - 512
  - 512
  data_layout: NCHW
  reverse_channels: false
  backend: cv2
  interpolation: 1
  add_flip_image: false
  resize_with_pad: false
  pad_color: 0
session:
  session_name: onnxrt
  work_dir: /opt/EdgeAIRoot/18423504/projects/25cd3020/run/20250702-165413/deeplabv3plus_mobilenetv2_tv_edgeailite/compilation/AM69A/work
  target_machine: pc
  target_device: AM69A
  run_suffix: null
  tidl_offload: true
  input_optimization: true
  input_data_layout: NCHW
  input_mean: null
  input_scale: null
  run_dir_tree_depth: 3
  runtime_options:
    platform: J7
    version: 9.1.0
    tidl_tools_path: /opt/edgeai-benchmark/tools/AM69A/tidl_tools
    artifacts_folder: /opt/EdgeAIRoot/18423504/projects/25cd3020/run/20250702-165413/deeplabv3plus_mobilenetv2_tv_edgeailite/compilation/AM69A/work/ss-8710/artifacts
    tensor_bits: 8
    import: 'yes'
    accuracy_level: 1
    debug_level: 0
    inference_mode: 0
    advanced_options:high_resolution_optimization: 0
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:calibration_frames: 12
    advanced_options:calibration_iterations: 12
    advanced_options:quantization_scale_type: 4
    advanced_options:activation_clipping: 1
    advanced_options:weight_clipping: 1
    advanced_options:bias_calibration: 1
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
    advanced_options:add_data_convert_ops: 3
    ti_internal_nc_flag: 83886080
    advanced_options:quant_params_proto_path: /opt/EdgeAIRoot/18423504/projects/25cd3020/run/20250702-165413/deeplabv3plus_mobilenetv2_tv_edgeailite/compilation/AM69A/work/ss-8710/model/model_best_qparams.prototxt
  model_path: /opt/EdgeAIRoot/18423504/projects/25cd3020/run/20250702-165413/deeplabv3plus_mobilenetv2_tv_edgeailite/training/model_best.onnx
  tidl_tools_path: /opt/edgeai-benchmark/tools/AM69A/tidl_tools
  run_dir: /opt/EdgeAIRoot/18423504/projects/25cd3020/run/20250702-165413/deeplabv3plus_mobilenetv2_tv_edgeailite/compilation/AM69A/work/ss-8710
  num_tidl_subgraphs: 16
  model_id: ss-8710
  model_type: null
  input_details:
  - name: input.1Net_IN
    shape:
    - 1
    - 3
    - 512
    - 512
    type: tensor(uint8)
  output_details:
  - name: 556TIDL_cast_out
    shape:
    - 1
    - 1
    - 1
    - 1
    - 512
    - 512
    type: tensor(uint8)
  num_inputs: 1
  extra_inputs: null
  tensor_bits: 8
  quant_params_proto_path: true
  supported_machines: null
  with_onnxsim: false
  shape_inference: true
  artifacts_folder: /opt/EdgeAIRoot/18423504/projects/25cd3020/run/20250702-165413/deeplabv3plus_mobilenetv2_tv_edgeailite/compilation/AM69A/work/ss-8710/artifacts
  model_folder: /opt/EdgeAIRoot/18423504/projects/25cd3020/run/20250702-165413/deeplabv3plus_mobilenetv2_tv_edgeailite/compilation/AM69A/work/ss-8710/model
  model_file: /opt/EdgeAIRoot/18423504/projects/25cd3020/run/20250702-165413/deeplabv3plus_mobilenetv2_tv_edgeailite/compilation/AM69A/work/ss-8710/model/model_best.onnx
postprocess:
  data_layout: NCHW
  save_output: true
  with_argmax: true
model_info:
  metric_reference:
    accuracy_mean_iou%: null
  model_shortlist: 20
metric:
  label_offset_pred: 0
