calibration_dataset:
  annotation_prefix: instances
  dataset_info: /root/compiled_onnxrt_AM69A/dataset.yaml
  num_classes: null
  num_frames: 25
  path: /opt/EdgeAIRoot/18423504/projects/25cd3020/dataset
  shuffle: true
  split: train
dataset_category: cocoseg21
input_dataset:
  annotation_prefix: instances
  dataset_info: /root/compiled_onnxrt_AM69A/dataset.yaml
  name: modelmaker_seg
  num_classes: null
  num_frames: 134
  path: /opt/EdgeAIRoot/18423504/projects/25cd3020/dataset
  shuffle: false
  split: val
metric:
  label_offset_pred: 0
  run_dir: /opt/EdgeAIRoot/18423504/projects/25cd3020/run/20250702-165413/deeplabv3plus_mobilenetv2_tv_edgeailite/compilation/AM69A/work/ss-8710
model_info:
  metric_reference:
    accuracy_mean_iou%: null
  model_shortlist: 20
postprocess:
  data_layout: NCHW
  save_output: true
  with_argmax: true
preprocess:
  add_flip_image: false
  backend: cv2
  crop:
  - 512
  - 512
  data_layout: NCHW
  interpolation: 1
  pad_color: 0
  resize:
  - 512
  - 512
  resize_with_pad: false
  reverse_channels: false
session:
  artifacts_folder: artifacts
  extra_inputs: null
  input_data_layout: NCHW
  input_details:
  - name: input.1Net_IN
    shape:
    - 1
    - 3
    - 512
    - 512
    type: tensor(uint8)
  input_mean: null
  input_optimization: true
  input_scale: null
  model_file: /root/compiled_onnxrt_AM69A/model/model_best.onnx
  model_folder: model
  model_id: ss-8710
  model_path: model/model_best.onnx
  model_type: null
  num_inputs: 1
  num_tidl_subgraphs: 16
  output_details:
  - name: 556TIDL_cast_out
    shape:
    - 1
    - 1
    - 1
    - 1
    - 512
    - 512
    type: tensor(uint8)
  quant_params_proto_path: true
  run_dir: ss-8710
  run_dir_tree_depth: 3
  run_suffix: null
  runtime_options:
    accuracy_level: 1
    advanced_options:activation_clipping: 1
    advanced_options:add_data_convert_ops: 3
    advanced_options:bias_calibration: 1
    advanced_options:calibration_frames: 12
    advanced_options:calibration_iterations: 12
    advanced_options:high_resolution_optimization: 0
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:quant_params_proto_path: /root/compiled_onnxrt_AM69A/model/model_best_qparams.prototxt
    advanced_options:quantization_scale_type: 4
    advanced_options:weight_clipping: 1
    artifacts_folder: /root/compiled_onnxrt_AM69A/artifacts
    debug_level: 0
    import: 'no'
    inference_mode: 0
    platform: J7
    tensor_bits: 8
    ti_internal_nc_flag: 83886080
    tidl_tools_path: /opt/edgeai-benchmark/tools/AM69A/tidl_tools
    version: 9.1.0
  session_name: onnxrt
  shape_inference: true
  supported_machines: null
  target_device: AM69A
  target_machine: pc
  tensor_bits: 8
  tidl_offload: true
  tidl_tools_path: /opt/edgeai-benchmark/tools/AM69A/tidl_tools
  with_onnxsim: false
  work_dir: /opt/EdgeAIRoot/18423504/projects/25cd3020/run/20250702-165413/deeplabv3plus_mobilenetv2_tv_edgeailite/compilation/AM69A/work
task_type: segmentation
